name: Django CI/CD

on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        set -ex
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install ./google-chrome-stable_current_amd64.deb
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install msedge-selenium-tools
    - uses: nanasess/setup-chromedriver@v2
    - run: |
        chromedriver --url-base=/wd/hub &
    - name: Run local Server
      run: |
        python manage.py runserver &
        sleep 5
        python manage.py test
    - uses: actions/checkout@v2
    - name: Django EB Deploy
      uses: joel-hanson/django-aws-eb-deploy@V1.1
      with:
        python_version: ${{ matrix.python_version }}
        flake8: true
        aws_access_key_id: ${{ secrets.aws_access_key_id }}
        aws_secret_access_key: ${{ secrets.aws_secret_access_key }}
        django_path: sample_project
        unit_testing: false
        deploy: true
        min_coverage: 10
        security_check: false
    
